# Home Assistant Main Configuration File
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  elevation: 63
  unit_system: metric
  time_zone: !secret time_zone
frontend:
config:
cloud: # https://www.home-assistant.io/integrations/cloud/
mobile_app: # https://www.home-assistant.io/integrations/mobile_app/
#https://home-assistant.io/components/recorder/
recorder:
  purge_keep_days: 3
  db_url: !secret db_url

# https://www.home-assistant.io/integrations/prometheus/
prometheus:
  namespace: hass
  # component_config_glob:
  #   sensor.*_hum:
  #     override_metric: humidity_percent
  #   sensor.*_temp:
  #     override_metric: temperature_c
  #   sensor.temperature*:
  #     override_metric: temperature_c
  #   sensor.*_bat:
  #     override_metric: battery_percent
  # filter:
  #   include_domains:
  #     - sensor
  #   exclude_entity_globs:
  #     - sensor.weather_*
# InfluxDB Addon
influxdb:
  host: a0d7b954_influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_pw
  max_retries: 3
  default_measurement: state

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml

#Broadlink RM Pro infra red https://www.home-assistant.io/integrations/broadlink/
remote:
  - platform: broadlink
    host: !secret broadlink_hostip
    mac: !secret broadlink_mac
    name: broadlink_livingroom

# https://www.home-assistant.io/integrations/webostv/
webostv:
  name: Living Room TV
  host: !secret ip_vlan100_121
