# Home Assistant Main Configuration File
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  elevation: 63
  unit_system: metric
  time_zone: !secret time_zone
frontend:
config:
logbook:
cloud: # https://www.home-assistant.io/integrations/cloud/
mobile_app: # https://www.home-assistant.io/integrations/mobile_app/
history: #https://home-assistant.io/components/history/
recorder: #https://home-assistant.io/components/recorder/
  purge_keep_days: 3
  db_url: !secret db_url
system_health:
person:
default_config:

# https://www.home-assistant.io/integrations/prometheus/
prometheus:
  namespace: hass
  # component_config_glob:
  #   sensor.*_hum:
  #     override_metric: humidity_percent
  #   sensor.*_temp:
  #     override_metric: temperature_c
  #   sensor.temperature*:
  #     override_metric: temperature_c
  #   sensor.*_bat:
  #     override_metric: battery_percent
  # filter:
  #   include_domains:
  #     - sensor
  #   exclude_entity_globs:
  #     - sensor.weather_*
# InfluxDB Addon
influxdb:
  host: !secret hassio_hostname
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_pw
  max_retries: 5
  default_measurement: state

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml
sensor: !include sensors.yaml

#Broadlink RM Pro infra red https://www.home-assistant.io/integrations/broadlink/
remote:
  - platform: broadlink
    host: !secret broadlink_hostip
    mac: !secret broadlink_mac
    name: broadlink_livingroom

# https://www.home-assistant.io/integrations/webostv/
webostv:
  name: Living Room TV
  host: !secret ip_vlan100_121

light:
  - platform: flux_led
    devices:
      192.168.0.189:
        name: flux_playarea
      192.168.0.184:
        name: flux_fireplace

  # - platform: group
  #   name: Kitchen lights
  #   entities:
  #     - light.kitchen_island
  #     - light.kitchen_lights

  # - platform: group
  #   name: Living room lights
  #   entities:
  #     - light.living_room_corner
  #     - light.living_room_side

  # - platform: group
  #   name: Hallway lights
  #   entities:
  #     - light.hallway
  #     - light.hallway_1
  #     - light.hallway_2
  #     - light.hallway_3
  #     - light.hallway_4
  #     - light.hallway_5
  #     - light.hallway_6
  #     - light.hallway_7
  #     - light.hallway_far

  # - platform: group
  #   name: Kitchen Lights
  #   entities:
  #     - light.kitchen_island
  #     - light.kitchen_lights

  # - platform: group
  #   name: Garden Lights
  #   entities:
  #     - light.garden_left
  #     - light.garden_right

tplink:
  discovery: false
  switch:
    - host: !secret ip_vlan100_110
    - host: !secret ip_vlan100_111
    - host: !secret ip_vlan100_112
# Nest
nest:
  client_id: !secret api_user_nest
  client_secret: !secret api_sec_nest

# Ping Cloudflare
binary_sensor:
  - platform: ping
    host: 1.1.1.1
    scan_interval: 5
    name: "The Internet"

###########################################################
# Media Players
############################################################
media_player:
  #Sony TV
  - platform: braviatv
    host: !secret ip_vlan100_166
    name: Sony TV Bedroom

  #VirginTV
  - platform: virgintivo
    default_is_show: false
    #show_packages: Free-to-air,Player,Mix,Fun,Full House,Premium,Pay-per-view
    show_packages: Free-to-air
    scan_interval: 7
    # default_is_hd: true
    tivos:
      1:
        name: Virgin TV Box
        host: !secret ip_vlan100_205
    guide:
      picture_refresh: 30
    channels:
      101:
        name: BBC One
        show: true
        hd_channel: 108
      102:
        name: BBC Two
        show: true
        hd_channel: 162
      103:
        name: ITV
        show: true
        hd_channel: 113
        plus_one: 114
      104:
        name: Channel 4
        show: true
        hd_channel: 141
        plus_one: 142
      141:
        name: Channel 4 HD
        show: true
        hd_channel: 141
      105:
        name: Channel 5
        show: true
        hd_channel: 150
        plus_one: 155
      106:
        name: E4
        show: true
        hd_channel: 145
        plus_one: 146
      107:
        name: BBC Four
        hd_channel: 163
      108:
        name: BBC One HD

# Speedtest https://www.home-assistant.io/components/sensor.speedtest
speedtestdotnet:
  scan_interval:
    minutes: 240
  monitored_conditions:
    - ping
    - download
    - upload

mqtt:
  discovery: true
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"
