- platform: broadlink
  mac: !secret broadlink_mac
  switches:
    # Infra Red Codes learned from BRIO IR 102 railway engine
    # https://www.brio.net/products/all-products/railway/trains-wagon--vehicles/remote-control-engine
    # Channel A switch enabled
    train_a_horn:
      friendly_name: "train a horn"
      command_on: "JgAoAMkOMBMULzEUETEwExQvMRQzAAU9yA4xEhA0MBIQNDESEDMxEjMADQU="
    train_a_lights:
      friendly_name: "train a lights"
      command_on: "JgAoAMgONRARMTIRFC8ULzMSMw8yAAU+yBEzEA4zMxEULw80NQ4yEjQADQU="
    train_a_go:
      friendly_name: "train a go"
      command_on: "JgAoAMgOMxEULzITDjMzETQQEDIRAAVgyA4yEg80MhERMjIRMhMONBMADQU="
    train_a_fast:
      friendly_name: "train a fast"
      command_on: "JgAoAMgQMw8ULzMSETExEjMRMxEQAAVdyQ8zDxQwNBARMTQPNBExEhAADQU="
    train_a_reverse:
      friendly_name: "train a reverse"
      command_on: "JgAoAMcQMhERMjESEjIwEjMREjExAAVBxhEwExAzMBMTMTATMBMQMzIADQU="
    train_a_stop:
      friendly_name: "train a stop"
      command_on: "JgAoAMcRMxEQMTETEzAzEjMOMRQzAAU7xxIzDhIxMRQRMTQPMhE1EDMADQU="
    # Channel B switch enabled, if only one train you can add both codes to be sent on send.
    train_b_horn:
      friendly_name: "train b horn"
      command_on: "JgAUAMYRETIzEBIxMxEzEBIxMhEzAA0FAAAAAA=="
    train_b_lights:
      friendly_name: "train b lights"
      command_on: "JgAUAMcQEjEyERMxMxASMTIRMxIyAA0FAAAAAA=="
    train_b_go:
      friendly_name: "train b go"
      command_on: "JgAUAMcQEjEzEBEyMxAzETMQETISAA0FAAAAAA=="
    train_b_fast:
      friendly_name: "train b fast"
      command_on: "JgAUAMcPEzEzEQ40MxAzEDMRMxASAA0FAAAAAA=="
    train_b_reverse:
      friendly_name: "train b reverse"
      command_on: "JgAUAMcPEzEzEBIxNA8zETMQEjE0AA0FAAAAAA=="
    train_b_stop:
      friendly_name: "train b stop"
      command_on: "JgAUAMgPEjE0ERExMxAxEjQRMhEzAA0FAAAAAA=="
