- platform: broadlink
  host: !secret broadlink_hostip #living_room
  mac: !secret broadlink_mac
  switches:
    # https://www.brio.net/products/all-products/railway/trains-wagon--vehicles/remote-control-engine
    # Infra Red Codes learned from BRIO IR 102 railway engine
    # Channel A
    locamotive_horn_ch_a:
      friendly_name: "Locomotive horn channel a"
      command_on: "JgAoAMkOMBMULzEUETEwExQvMRQzAAU9yA4xEhA0MBIQNDESEDMxEjMADQU="
    locamotive_lights_ch_a:
      friendly_name: "Locomotive lights channel a"
      command_on: "JgAoAMgONRARMTIRFC8ULzMSMw8yAAU+yBEzEA4zMxEULw80NQ4yEjQADQU="
    locamotive_forward1x_ch_a:
      friendly_name: "Locomotive forward 1x channel a"
      command_on: "JgAoAMgOMxEULzITDjMzETQQEDIRAAVgyA4yEg80MhERMjIRMhMONBMADQU="
    locamotive_forward2x_ch_a:
      friendly_name: "Locomotive forward 2x channel a"
      command_on: "JgAoAMgQMw8ULzMSETExEjMRMxEQAAVdyQ8zDxQwNBARMTQPNBExEhAADQU="
    locamotive_reverse_ch_a:
      friendly_name: "Locomotive reverse channel a"
      command_on: "JgAoAMcQMhERMjESEjIwEjMREjExAAVBxhEwExAzMBMTMTATMBMQMzIADQU="
    locamotive_stop_ch_a:
      friendly_name: "Locomotive stop channel a"
      command_on: "JgAoAMcRMxEQMTETEzAzEjMOMRQzAAU7xxIzDhIxMRQRMTQPMhE1EDMADQU="
    # Channel B
    locamotive_horn_ch_b:
      friendly_name: "Locomotive horn channel b"
      command_on: "JgAUAMYRETIzEBIxMxEzEBIxMhEzAA0FAAAAAA=="
    locamotive_lights_ch_b:
      friendly_name: "Locomotive lights channel b"
      command_on: "JgAUAMcQEjEyERMxMxASMTIRMxIyAA0FAAAAAA=="
    locamotive_forward1x_ch_b:
      friendly_name: "Locomotive forward 1x channel b"
      command_on: "JgAUAMcQEjEzEBEyMxAzETMQETISAA0FAAAAAA=="
    locamotive_forward2x_ch_b:
      friendly_name: "Locomotive forward 2x channel b"
      command_on: "JgAUAMcPEzEzEQ40MxAzEDMRMxASAA0FAAAAAA=="
    locamotive_reverse_ch_b:
      friendly_name: "Locomotive reverse channel b"
      command_on: "JgAUAMcPEzEzEBIxNA8zETMQEjE0AA0FAAAAAA=="
    locamotive_stop_ch_b:
      friendly_name: "Locomotive stop channel b"
      command_on: "JgAUAMgPEjE0ERExMxAxEjQRMhEzAA0FAAAAAA=="
